### ISSUE TITLE
Unique abbreviations

### ISSUE THREAD

**Issue by snoblenet** [kachick/abb#1]
Hi there,

Is there any way to ensure this generates unique abbreviations within a defined scope?

Thanks,

Steven.

**Comment by kachick** [comment]
@snoblenet Sorry for late reply! This library does not have the feature. But hacks so easy. I have written the example :) https://github.com/kachick/abb/blob/4a6d8c40667dc38abc73839a2d3eeff40ee544df/examples/check_unique_abb.rb
